/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient;


namespace AGVSystemCommonNet6.GPMRosMessageNet.SickSafetyscanners
{
    public class DataHeaderMsg : Message
    {
        public const string RosMessageName = "sick_safetyscanners/DataHeaderMsg";

        public byte version_version { get; set; }
        public byte version_major_version { get; set; }
        public byte version_minor_version { get; set; }
        public byte version_release { get; set; }
        public uint serial_number_of_device { get; set; }
        public uint serial_number_of_channel_plug { get; set; }
        public byte channel_number { get; set; }
        public uint sequence_number { get; set; }
        public uint scan_number { get; set; }
        public ushort timestamp_date { get; set; }
        public uint timestamp_time { get; set; }

        public DataHeaderMsg()
        {
            this.version_version = 0;
            this.version_major_version = 0;
            this.version_minor_version = 0;
            this.version_release = 0;
            this.serial_number_of_device = 0;
            this.serial_number_of_channel_plug = 0;
            this.channel_number = 0;
            this.sequence_number = 0;
            this.scan_number = 0;
            this.timestamp_date = 0;
            this.timestamp_time = 0;
        }

        public DataHeaderMsg(byte version_version, byte version_major_version, byte version_minor_version, byte version_release, uint serial_number_of_device, uint serial_number_of_channel_plug, byte channel_number, uint sequence_number, uint scan_number, ushort timestamp_date, uint timestamp_time)
        {
            this.version_version = version_version;
            this.version_major_version = version_major_version;
            this.version_minor_version = version_minor_version;
            this.version_release = version_release;
            this.serial_number_of_device = serial_number_of_device;
            this.serial_number_of_channel_plug = serial_number_of_channel_plug;
            this.channel_number = channel_number;
            this.sequence_number = sequence_number;
            this.scan_number = scan_number;
            this.timestamp_date = timestamp_date;
            this.timestamp_time = timestamp_time;
        }
    }
}
