/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */


using RosSharp.RosBridgeClient;

namespace AGVSystemCommonNet6.GPMRosMessageNet.SickSafetyscanners
{
    public class FieldMsg : Message
    {
        public const string RosMessageName = "sick_safetyscanners/FieldMsg";

        public float[] ranges { get; set; }
        public float start_angle { get; set; }
        public float angular_resolution { get; set; }
        public bool protective_field { get; set; }

        public FieldMsg()
        {
            this.ranges = new float[0];
            this.start_angle = 0.0f;
            this.angular_resolution = 0.0f;
            this.protective_field = false;
        }

        public FieldMsg(float[] ranges, float start_angle, float angular_resolution, bool protective_field)
        {
            this.ranges = ranges;
            this.start_angle = start_angle;
            this.angular_resolution = angular_resolution;
            this.protective_field = protective_field;
        }
    }
}
