/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */


using RosSharp.RosBridgeClient;

namespace AGVSystemCommonNet6.GPMRosMessageNet.SickSafetyscanners
{
    public class GeneralSystemStateMsg : Message
    {
        public const string RosMessageName = "sick_safetyscanners/GeneralSystemStateMsg";

        public bool run_mode_active { get; set; }
        public bool standby_mode_active { get; set; }
        public bool contamination_warning { get; set; }
        public bool contamination_error { get; set; }
        public bool reference_contour_status { get; set; }
        public bool manipulation_status { get; set; }
        public bool[] safe_cut_off_path { get; set; }
        public bool[] non_safe_cut_off_path { get; set; }
        public bool[] reset_required_cut_off_path { get; set; }
        public byte current_monitoring_case_no_table_1 { get; set; }
        public byte current_monitoring_case_no_table_2 { get; set; }
        public byte current_monitoring_case_no_table_3 { get; set; }
        public byte current_monitoring_case_no_table_4 { get; set; }
        public bool application_error { get; set; }
        public bool device_error { get; set; }

        public GeneralSystemStateMsg()
        {
            this.run_mode_active = false;
            this.standby_mode_active = false;
            this.contamination_warning = false;
            this.contamination_error = false;
            this.reference_contour_status = false;
            this.manipulation_status = false;
            this.safe_cut_off_path = new bool[0];
            this.non_safe_cut_off_path = new bool[0];
            this.reset_required_cut_off_path = new bool[0];
            this.current_monitoring_case_no_table_1 = 0;
            this.current_monitoring_case_no_table_2 = 0;
            this.current_monitoring_case_no_table_3 = 0;
            this.current_monitoring_case_no_table_4 = 0;
            this.application_error = false;
            this.device_error = false;
        }

        public GeneralSystemStateMsg(bool run_mode_active, bool standby_mode_active, bool contamination_warning, bool contamination_error, bool reference_contour_status, bool manipulation_status, bool[] safe_cut_off_path, bool[] non_safe_cut_off_path, bool[] reset_required_cut_off_path, byte current_monitoring_case_no_table_1, byte current_monitoring_case_no_table_2, byte current_monitoring_case_no_table_3, byte current_monitoring_case_no_table_4, bool application_error, bool device_error)
        {
            this.run_mode_active = run_mode_active;
            this.standby_mode_active = standby_mode_active;
            this.contamination_warning = contamination_warning;
            this.contamination_error = contamination_error;
            this.reference_contour_status = reference_contour_status;
            this.manipulation_status = manipulation_status;
            this.safe_cut_off_path = safe_cut_off_path;
            this.non_safe_cut_off_path = non_safe_cut_off_path;
            this.reset_required_cut_off_path = reset_required_cut_off_path;
            this.current_monitoring_case_no_table_1 = current_monitoring_case_no_table_1;
            this.current_monitoring_case_no_table_2 = current_monitoring_case_no_table_2;
            this.current_monitoring_case_no_table_3 = current_monitoring_case_no_table_3;
            this.current_monitoring_case_no_table_4 = current_monitoring_case_no_table_4;
            this.application_error = application_error;
            this.device_error = device_error;
        }
    }
}
