/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient;


namespace AGVSystemCommonNet6.GPMRosMessageNet.SickSafetyscanners
{
    public class MonitoringCaseMsg : Message
    {
        public const string RosMessageName = "sick_safetyscanners/MonitoringCaseMsg";

        public int monitoring_case_number { get; set; }
        public int[] fields { get; set; }
        public bool[] fields_valid { get; set; }

        public MonitoringCaseMsg()
        {
            this.monitoring_case_number = 0;
            this.fields = new int[0];
            this.fields_valid = new bool[0];
        }

        public MonitoringCaseMsg(int monitoring_case_number, int[] fields, bool[] fields_valid)
        {
            this.monitoring_case_number = monitoring_case_number;
            this.fields = fields;
            this.fields_valid = fields_valid;
        }
    }
}
