/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */


using RosSharp.RosBridgeClient;

namespace AGVSystemCommonNet6.GPMRosMessageNet.SickSafetyscanners
{
    public class RawMicroScanDataMsg : Message
    {
        public const string RosMessageName = "sick_safetyscanners/RawMicroScanDataMsg";

        public DataHeaderMsg header { get; set; }
        public DerivedValuesMsg derived_values { get; set; }
        public GeneralSystemStateMsg general_system_state { get; set; }
        public MeasurementDataMsg measurement_data { get; set; }
        public IntrusionDataMsg intrusion_data { get; set; }
        public ApplicationDataMsg application_data { get; set; }

        public RawMicroScanDataMsg()
        {
            this.header = new DataHeaderMsg();
            this.derived_values = new DerivedValuesMsg();
            this.general_system_state = new GeneralSystemStateMsg();
            this.measurement_data = new MeasurementDataMsg();
            this.intrusion_data = new IntrusionDataMsg();
            this.application_data = new ApplicationDataMsg();
        }

        public RawMicroScanDataMsg(DataHeaderMsg header, DerivedValuesMsg derived_values, GeneralSystemStateMsg general_system_state, MeasurementDataMsg measurement_data, IntrusionDataMsg intrusion_data, ApplicationDataMsg application_data)
        {
            this.header = header;
            this.derived_values = derived_values;
            this.general_system_state = general_system_state;
            this.measurement_data = measurement_data;
            this.intrusion_data = intrusion_data;
            this.application_data = application_data;
        }
    }
}
