/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */


using RosSharp.RosBridgeClient;

namespace AGVSystemCommonNet6.GPMRosMessageNet.SickSafetyscanners
{
    public class ScanPointMsg : Message
    {
        public const string RosMessageName = "sick_safetyscanners/ScanPointMsg";

        public float angle { get; set; }
        public ushort distance { get; set; }
        public byte reflectivity { get; set; }
        public bool valid { get; set; }
        public bool infinite { get; set; }
        public bool glare { get; set; }
        public bool reflector { get; set; }
        public bool contamination { get; set; }
        public bool contamination_warning { get; set; }

        public ScanPointMsg()
        {
            this.angle = 0.0f;
            this.distance = 0;
            this.reflectivity = 0;
            this.valid = false;
            this.infinite = false;
            this.glare = false;
            this.reflector = false;
            this.contamination = false;
            this.contamination_warning = false;
        }

        public ScanPointMsg(float angle, ushort distance, byte reflectivity, bool valid, bool infinite, bool glare, bool reflector, bool contamination, bool contamination_warning)
        {
            this.angle = angle;
            this.distance = distance;
            this.reflectivity = reflectivity;
            this.valid = valid;
            this.infinite = infinite;
            this.glare = glare;
            this.reflector = reflector;
            this.contamination = contamination;
            this.contamination_warning = contamination_warning;
        }
    }
}
