// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AGVSystemCommonNet6.PartsModels
{
    public partial class AgvchargeStation
    {
        public string Agvname { get; set; }
        public string ChargeStation { get; set; }
    }
}