// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AGVSystemCommonNet6.PartsModels
{
    public partial class Agvinfo
    {
        public string Agvindex { get; set; }
        public string Agvnumber { get; set; }
        public string Agvname { get; set; }
        public string CurrentTagNumber { get; set; }
        public string Agvstatus { get; set; }
        public double? Agvbattery { get; set; }
        public string AgvwarningStatus { get; set; }
        public string Stage1Cstid { get; set; }
        public string Stage2Cstid { get; set; }
        public string Stage3Cstid { get; set; }
        public string Stage4Cstid { get; set; }
        public string DoTaskName { get; set; }
        public string AutoManual { get; set; }
        public string Agvtype { get; set; }
        public string DemoMode { get; set; }
    }
}