// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AGVSystemCommonNet6.PartsModels
{
    public partial class CartMaintainTable
    {
        public string CartName { get; set; }
        public double? NowMileage { get; set; }
        public double? LastMaintainMileage { get; set; }
        public DateTime? LastMaintainTime { get; set; }
    }
}