// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AGVSystemCommonNet6.PartsModels
{
    public partial class Dispatch
    {
        public string StationName { get; set; }
        public string AliveCheckIndex { get; set; }
        public string Fire { get; set; }
        public string ClearFlowTask { get; set; }
        public string CallEmptyCart { get; set; }
        public string ResendTaskMessage { get; set; }
        public string ClearTrafficRegistData { get; set; }
    }
}