// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AGVSystemCommonNet6.PartsModels
{
    public partial class EarthquakeLog
    {
        public DateTime? OccurTime { get; set; }
        public string Ip { get; set; }
        public string Message { get; set; }
        public string IsSendToAgv { get; set; }
    }
}