// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AGVSystemCommonNet6.PartsModels
{
    public partial class ElevatorWithAgvinfo
    {
        public string ElevatorName { get; set; }
        public string ExecuteAgv { get; set; }
        public string ExecuteGoFloor { get; set; }
    }
}