// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AGVSystemCommonNet6.PartsModels
{
    public partial class ElevatorInfo
    {
        public string ElevatorIndex { get; set; }
        public string ElevatorName { get; set; }
        public string ElevatorStatus { get; set; }
        public string EFloorStatus { get; set; }
        public string EDoorStatus { get; set; }
        public string ModeStatus { get; set; }
        public string DoTaskName { get; set; }
    }
}