// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AGVSystemCommonNet6.PartsModels
{
    public partial class FireAlarmLog
    {
        public DateTime? OccurTime { get; set; }
        public string Channel { get; set; }
        public string Station { get; set; }
        public string StatusFlag { get; set; }
        public string IsSendToAgv { get; set; }
    }
}