// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AGVSystemCommonNet6.PartsModels
{
    public partial class Hidlog
    {
        public DateTime? DateTime { get; set; }
        public string Hid { get; set; }
        public string BoxId { get; set; }
        public string PortName { get; set; }
        public string Action { get; set; }
    }
}