// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AGVSystemCommonNet6.PartsModels
{
    public partial class MaterialStationInfo
    {
        public DateTime? RecvTime { get; set; }
        public string MaterialStation { get; set; }
        public string Flag { get; set; }
        public string BoxId { get; set; }
        public string Lock { get; set; }
        public string Lift { get; set; }
        public string Enable { get; set; }
        public string AutoManualMode { get; set; }
        public string MaterialStationType { get; set; }
        public string NeedTagCart { get; set; }
        public string Size { get; set; }
        public string AvaliableCartSize { get; set; }
    }
}