// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AGVSystemCommonNet6.PartsModels
{
    public partial class MaterialWip
    {
        public string BoxId { get; set; }
        public string Wipflag { get; set; }
        public string Cstid { get; set; }
        public string Mrlist { get; set; }
        public string BoxIdtype { get; set; }
        public string MaterialStation { get; set; }
        public string IsGdas { get; set; }
    }
}