// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AGVSystemCommonNet6.PartsModels
{
    public partial class RackInfo
    {
        public string RackName { get; set; }
        public string RackNumber { get; set; }
        public string ExistFlag { get; set; }
    }
}