// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AGVSystemCommonNet6.PartsModels
{
    public partial class RunStatus
    {
        public long? Agvindex { get; set; }
        public DateTime? RecDateTime { get; set; }
        public string Agvname { get; set; }
        public int? Agvstatus { get; set; }
        public int? IdlePeriod { get; set; }
        public int? RunPeriod { get; set; }
        public int? DownPeriod { get; set; }
        public int? ChargingPeriod { get; set; }
        public int? EscapePeriod { get; set; }
        public int? StartMotorEncoder { get; set; }
        public int? EndMotorEncoder { get; set; }
        public DateTime? StartDateTime { get; set; }
    }
}