// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AGVSystemCommonNet6.PartsModels
{
    public partial class TrafficManager
    {
        public string Agvname { get; set; }
        public string Region { get; set; }
        public string ExecuteRoute { get; set; }
        public DateTime? RegistTime { get; set; }
        public int? Sequence { get; set; }
    }
}