// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AGVSystemCommonNet6.PartsModels
{
    public partial class UserInfo
    {
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string UserLayer { get; set; }
    }
}