using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AGVSystemCommonNet6.Alarm
{
    public enum ALARM_LEVEL
    {
        WARNING,
        ALARM,
    }
    public enum ALARM_SOURCE
    {
        AGVS, EQP
    }

    public enum ALARMS
    {
        NONE = 0,
        VMS_DISCONNECT = 2,
        AGV_DISCONNECT = 3,
        GET_ONLINE_REQ_BUT_AGV_DISCONNECT = 4,
        GET_OFFLINE_REQ_BUT_AGV_DISCONNECT = 5,
        GET_ONLINE_REQ_BUT_AGV_STATE_ERROR = 6,
        TRAFFIC_BLOCKED_NO_PATH_FOR_NAVIGATOR = 7,
        NO_AVAILABLE_CHARGE_PILE = 8,
        TRAFFIC_CONTROL_CENTER_EXCEPTION_WHEN_CHECK_NAVIGATOR_PATH = 9,
        GET_CHARGE_TASK_BUT_AGV_CHARGING_ALREADY = 10,
        CST_STATUS_CHECK_FAIL = 11,
        Endpoint_EQ_NOT_CONNECTED = 12,
        EQ_LOAD_REQUEST_IS_NOT_ON = 14,
        EQ_UNLOAD_REQUEST_IS_NOT_ON = 15,
        TRANSFER_TASK_TO_VMS_BUT_ERROR_OCCUR = 16,
        DESTIN_TAG_IS_INVLID_FORMAT = 17,
        STATION_TYPE_CANNOT_USE_AUTO_SEARCH = 18,
        NO_AVAILABLE_PARK_STATION = 19,
        ERROR_WHEN_CREATE_NAVIGATION_JOBS_LINK = 20,
        EQ_UNLOAD_REQUEST_ON_BUT_TAG_NOT_EXIST_ON_MAP = 21,
        EQ_UNLOAD_REQUEST_ON_BUT_STATION_TYPE_SETTING_IS_NOT_EQ = 22,
        ERROR_WHEN_FIND_TAG_OF_STATION = 23,
        MAP_POINT_NO_TARGETS = 24,
        ERROR_WHEN_AGV_STATUS_WRITE_TO_DB = 25,
        TRAFFIC_ABORT = 26,
        GET_ONLINE_REQ_BUT_AGV_LOCATION_IS_TOO_FAR_FROM_POINT = 27,
        GET_ONLINE_REQ_BUT_AGV_LOCATION_IS_NOT_EXIST_ON_MAP = 28,
        GET_ONLINE_REQ_BUT_AGV_IS_NOT_REGISTED = 3029,
        CANNOT_DISPATCH_MOVE_TASK_IN_WORKSTATION = 3030,
        CANNOT_DISPATCH_LOAD_TASK_TO_NOT_EQ_STATION = 3031,
        CANNOT_DISPATCH_LOAD_TASK_WHEN_AGV_NO_CARGO = 3032,
        CANNOT_DISPATCH_UNLOAD_TASK_WHEN_AGV_HAS_CARGO = 3033,
        CANNOT_DISPATCH_UNLOAD_TASK_TO_NOT_EQ_STATION = 3034,
        CANNOT_DISPATCH_CHARGE_TASK_TO_NOT_CHARGABLE_STATION = 3035,
        CANNOT_DISPATCH_ORDER_BY_AGV_BAT_STATUS_CHECK = 3036,
        AGV_Task_Feedback_But_Task_Name_Not_Match = 36,
        SYSTEM_ERROR = 37,
        CANNOT_DISPATCH_INTO_WORKSTATION_TASK_WHEN_AGV_HAS_CARGO = 38,
        CANNOT_DISPATCH_NORMAL_MOVE_TASK_WHEN_DESTINE_IS_WORKSTATION = 39,
        EQ_TAG_NOT_EXIST_IN_CURRENT_MAP = 40,
        SubTask_Queue_Empty_But_Try_DownloadTask_To_AGV = 41,
        AGV_STATUS_DOWN = 42,
        CANNOT_DISPATCH_TASK_WITH_ILLEAGAL_STATUS = 43,
        AGV_BATTERY_LOW_LEVEL = 44,
        AGV_WORKSTATION_DATA_NOT_SETTING = 45,
        AGV_AT_UNKNON_TAG_LOCATION = 46,
        Task_Status_Cant_Save_To_Database = 47,
        Task_Cancel_Fail = 48,
        Task_Add_To_Database_Fail = 49,
        AGV_TCPIP_DISCONNECT = 50,
        Save_Measure_Data_to_DB_Fail = 51,
        Region_Has_No_Agv_To_Dispatch_Task = 52,
        CANNOT_DISPATCH_CARRY_TASK_WHEN_AGV_HAS_CARGO = 53,
        CANNOT_DISPATCH_LOCAL_AUTO_TRANSFER_TASK = 54,
        Source_Eq_Unload_Request_Off = 55,
        Destine_Eq_Load_Request_Off = 56,
        Source_Eq_Status_Down = 57,
        Destine_Eq_Status_Down = 58,
        Cannot_Auto_Parking_When_AGV_Has_Cargo = 59,
        Destine_Eq_Already_Has_Task_To_Excute = 60,
        Destine_EQ_Has_AGV = 61,
        Destine_EQ_Has_Registed = 62,
        UNLOAD_BUT_AGV_NO_CARGO_MOUNTED = 63,
        UNLOAD_BUT_CARGO_ID_EMPTY = 64,
        UNLOAD_BUT_CARGO_ID_NOT_MATCHED = 65,
        TASK_DOWNLOAD_DATA_ILLEAGAL = 66,
        AGV_TaskFeedback_ERROR = 67,
        EQ_Disconnect = 68,
        ERROR_WHEN_TASK_STATUS_CHAGE_DB = 69,
        Destine_Normal_Station_Has_Task_To_Reach = 70,
        Destine_Eq_Station_Has_Task_To_Park = 71,
        Destine_Charge_Station_Has_AGV = 72,
        PING_CHECK_FAIL = 73,
        Download_Task_To_AGV_Fail = 74,
        EQ_LOAD_REQUEST_ON_BUT_HAS_CARGO = 75,
        EQ_UNLOAD_REQUEST_ON_BUT_NO_CARGO = 76,
        EQ_UNLOAD_REQUEST_ON_BUT_POSE_NOT_UP = 76,
        EQ_LOAD_REQUEST_ON_BUT_POSE_NOT_DOWN = 76,
        EQ_UNLOAD_REQ_BUT_RACK_FULL_OR_EMPTY_IS_UNKNOWN = 77,
        EQ_LOAD_REQ_BUT_RACK_FULL_OR_EMPTY_IS_UNKNOWN = 78,
        AGV_Type_Is_Not_Allow_To_Execute_Task_At_Source_Equipment = 79,
        AGV_Type_Is_Not_Allow_To_Execute_Task_At_Destine_Equipment = 80,
        EQ_Input_Data_Not_Enough = 81,
        AGV_Already_Has_Charge_Task = 82,
        Charge_Station_Already_Has_Task_Assigned = 83,
        Charge_Station_Already_Has_AGV_Parked = 84,
        Station_Disabled = 85,
        TASK_DOWNLOAD_TO_AGV_FAIL_AGV_STATUS_DOWN = 86,
        TASK_DOWNLOAD_TO_AGV_FAIL = 87,
        TASK_DOWNLOAD_TO_AGV_FAIL_AGV_NOT_ON_TAG = 88,
        TASK_DOWNLOAD_TO_AGV_FAIL_WORKSTATION_NOT_SETTING_YET = 89,
        TASK_DOWNLOAD_TO_AGV_FAIL_AGV_BATTERY_LOW_LEVEL = 90,
        TASK_DOWNLOAD_TO_AGV_FAIL_AGV_CANNOT_GO_TO_WORKSTATION_WITH_NORMAL_MOVE_ACTION = 91,
        TASK_DOWNLOAD_TO_AGV_FAIL_TASK_DOWNLOAD_DATA_ILLEAGAL = 92,
        TASK_DOWNLOAD_TO_AGV_FAIL_SYSTEM_EXCEPTION = 93,
        TASK_DOWNLOAD_TO_AGV_FAIL_NO_PATH_FOR_NAVIGATION = 94,
        TASK_DOWNLOAD_TO_AGV_FAIL_TASK_CANCEL = 95,
        TASK_DOWNLOAD_TO_AGV_FAIL_TASK_DOWN_LOAD_TIMEOUT = 96,
        Task_Canceled = 97,
        CANT_AUTO_SEARCH_STATION_TYPE_IS_NOT_EXCHANGE_FOR_INSPECTION_AGV = 98,
        NO_AVAILABLE_BAT_EXCHANGER_USABLE = 99,
        REGIST_REGIONS_TO_PARTS_SYSTEM_FAIL = 100,
        SYSTEM_EQP_MANAGEMENT_INITIALIZE_FAIL_WITH_EXCEPTION = 101,
        INVALID_CHARGE_STATION = 102,
        Battery_Not_Connect = 3037,
        Rack_Port_Sensor_Flash = 3038,
        Transfer_Tags_Not_Found = 3039,
        No_Transfer_Station_To_Work = 3040,
        Task_Aborted = 3041,
        CANNOT_DISPATCH_CHARGE_TASK_WHEN_AGV_HAS_CARGO = 3042,
        VEHICLES_TRAJECTORY_CONFLIC = 3043,
        REGION_NOT_ENTERABLE = 3044,
    }

}
