using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AGVSystemCommonNet6.Alarm
{
    public class AlarmCodeTable
    {
        public static clsAlarmCode[] Table { get; set; } = new clsAlarmCode[]
        {
            new clsAlarmCode(ALARMS.CreateCommandFail, "派車系統發生程式上的Crash造成", "CreateCommandFail", "", "", ""),
            new clsAlarmCode(ALARMS.NoActionType, "沒有選擇或是無法辨識任務命令類別", "NoActionType", "", "", ""),
            new clsAlarmCode(ALARMS.EmptySourcePort, "沒有選擇任務起點", "EmptySourcePort", "", "", ""),
            new clsAlarmCode(ALARMS.NoDefineSourcePort, "沒有定義或無法辨識任務起點點位", "NoDefineSourcePort", "", "", ""),
            new clsAlarmCode(ALARMS.EmptyDestPort, "沒有選擇任務終點", "EmptyDestPort", "", "", ""),
            new clsAlarmCode(ALARMS.NoDefineDestPort, "沒有定義或無法辨識任務終點點位", "NoDefineDestPort", "", "", ""),
            new clsAlarmCode(ALARMS.WrongTypeOfSourcePort, "起點的站點種類與任務命令類別匹配錯誤", "WrongTypeOfSourcePort", "", "", ""),
            new clsAlarmCode(ALARMS.WrongTargetOfSourcePort, "起點無法找到有效之二次定位點", "WrongTargetOfSourcePort", "", "", ""),
            new clsAlarmCode(ALARMS.WrongTypeOfDestPort, "終點的站點種類與任務命令類別匹配錯誤", "WrongTypeOfDestPort", "", "", ""),
            new clsAlarmCode(ALARMS.WrongTargetOfDestPort, "終點無法找到有效之二次定位點", "WrongTargetOfDestPort", "", "", ""),
            new clsAlarmCode(ALARMS.SaveDBFail, "任務資料儲存至資料庫錯誤", "SaveDBFail", "", "", ""),
            new clsAlarmCode(ALARMS.WrongAssignVehilceID, "起點指定的車子與任務指定的車子不同", "WrongAssignVehilceID", "", "", ""),
            new clsAlarmCode(ALARMS.WrongVehicleCSTStatus, "起點為車子但無卡匣存在", "WrongVehicleCSTStatus", "", "", ""),
            new clsAlarmCode(ALARMS.DownloadTaskDataWrong, "檢查任務資料異常", "DownloadTaskDataWrong", "", "", ""),
            new clsAlarmCode(ALARMS.NoAssignVehicle, "沒有指定或指定的車子ID不存在", "NoAssignVehicle", "", "", ""),
            new clsAlarmCode(ALARMS.DownloadTaskNoCarrierID, "任務沒有指定的CarrierID", "DownloadTaskNoCarrierID", "", "", ""),
            new clsAlarmCode(ALARMS.CannotFindCommand, "於資料庫中找不到指定欲取消的任務", "CannotFindCommand", "", "", ""),
            new clsAlarmCode(ALARMS.WrongStatus, "於錯誤的狀態下取消任務", "WrongStatus", "", "", ""),
            new clsAlarmCode(ALARMS.LicenseErr, "找不到註冊碼", "License Err", "", "", ""),
            new clsAlarmCode(ALARMS.RunTimeErr, "執行階段錯誤", "Run Time Err", "", "", ""),
            new clsAlarmCode(ALARMS.ReloadLogiciniErr, "載入主設定檔時發生錯誤", "Reload Logic.ini Err", "", "", ""),
            new clsAlarmCode(ALARMS.MissAlarmini, "找不到異常碼設定檔", "Miss Alarm.ini", "", "", ""),
            new clsAlarmCode(ALARMS.NotFoundAlarmCode, "設定檔找不到指定的異常碼", "Not Found Alarm Code", "", "", ""),
            new clsAlarmCode(ALARMS.NotFoundAlarmText, "設定檔找不到指定的異常碼描述", "Not Found Alarm Text", "", "", ""),
            new clsAlarmCode(ALARMS.TrafficBookingTaskCannotFindVehicle, "交管系統註冊路徑回傳參數找不到指定車載", "Traffic Booking Task Cannot Find Vehicle", "", "", ""),
            new clsAlarmCode(ALARMS.CannotFindChargeStationInMap, "系統在地圖上找不到充電站", "Cannot Find Charge Station In Map", "", "", ""),
            new clsAlarmCode(ALARMS.CannotFindIdlePointInMap, "系統在地圖上找不到 Idle Point", "Cannot Find Idle Point In Map", "", "", ""),
            new clsAlarmCode(ALARMS.CannotFindParkingPointInMap, "系統在地圖上找不到 Parking Point", "Cannot Find Parking Point In Map", "", "", ""),
            new clsAlarmCode(ALARMS.REGION_NOT_ENTERABLE, "區域不可進入", "REGION_NOT_ENTERABLE", "", "", ""),
            new clsAlarmCode(ALARMS.From_To_Of_Transfer_Task_Is_Incorrectly, "轉移任務的起點和終點錯誤", "From_To_Of_Transfer_Task_Is_Incorrectly", "", "", ""),
            new clsAlarmCode(ALARMS.AGV_NO_Carge_Cannot_Transfer_Cargo_From_AGV_To_Desinte, "AGV 無貨物，無法從 AGV 轉移貨物至目標", "AGV_NO_Carge_Cannot_Transfer_Cargo_From_AGV_To_Desinte", "", "", ""),
            new clsAlarmCode(ALARMS.NONE, "無", "None", "", "", ""),
            new clsAlarmCode(ALARMS.AGVS_DISCONNECT_WITH_VMS, "AGVS 與 VMS 斷開連接", "AGVS Disconnect With VMS", "", "", ""),
            new clsAlarmCode(ALARMS.GET_ONLINE_REQ_BUT_AGV_DISCONNECT, "收到上線請求但 AGV 斷開連接", "Get Online Req But AGV Disconnect", "", "", ""),
            new clsAlarmCode(ALARMS.GET_OFFLINE_REQ_BUT_AGV_DISCONNECT, "收到下線請求但 AGV 斷開連接", "Get Offline Req But AGV Disconnect", "", "", ""),
            new clsAlarmCode(ALARMS.GET_ONLINE_REQ_BUT_AGV_STATE_ERROR, "收到上線請求但 AGV 狀態錯誤", "Get Online Req But AGV State Error", "", "", ""),
            new clsAlarmCode(ALARMS.TRAFFIC_BLOCKED_NO_PATH_FOR_NAVIGATOR, "導航器無法找到路徑", "Traffic Blocked No Path For Navigator", "", "", ""),
            new clsAlarmCode(ALARMS.NO_AVAILABLE_CHARGE_PILE, "沒有可用的充電樁", "No Available Charge Pile", "", "", ""),
            new clsAlarmCode(ALARMS.TRAFFIC_CONTROL_CENTER_EXCEPTION_WHEN_CHECK_NAVIGATOR_PATH, "檢查導航路徑時交通控制中心異常", "Traffic Control Center Exception When Check Navigator Path", "", "", ""),
            new clsAlarmCode(ALARMS.GET_CHARGE_TASK_BUT_AGV_CHARGING_ALREADY, "收到充電任務但 AGV 已在充電", "Get Charge Task But AGV Charging Already", "", "", ""),
            new clsAlarmCode(ALARMS.CST_STATUS_CHECK_FAIL, "CST 狀態檢查失敗", "CST Status Check Fail", "", "", ""),
            new clsAlarmCode(ALARMS.Endpoint_EQ_NOT_CONNECTED, "終端設備未連接", "Endpoint EQ Not Connected", "", "", ""),
            new clsAlarmCode(ALARMS.EQ_LOAD_REQUEST_IS_NOT_ON, "設備加載請求未啟動", "EQ Load Request Is Not On", "", "", ""),
            new clsAlarmCode(ALARMS.EQ_UNLOAD_REQUEST_IS_NOT_ON, "設備卸載請求未啟動", "EQ Unload Request Is Not On", "", "", ""),
            new clsAlarmCode(ALARMS.TRANSFER_TASK_TO_VMS_BUT_ERROR_OCCUR, "轉移任務到 VMS 時發生錯誤", "Transfer Task To VMS But Error Occur", "", "", ""),
            new clsAlarmCode(ALARMS.DESTIN_TAG_IS_INVLID_FORMAT, "目的地標籤格式無效", "Destin Tag Is Invalid Format", "", "", ""),
            new clsAlarmCode(ALARMS.STATION_TYPE_CANNOT_USE_AUTO_SEARCH, "站點類型無法使用自動搜索", "Station Type Cannot Use Auto Search", "", "", ""),
            new clsAlarmCode(ALARMS.NO_AVAILABLE_PARK_STATION, "沒有可用的停車站", "No Available Park Station", "", "", ""),
            new clsAlarmCode(ALARMS.ERROR_WHEN_CREATE_NAVIGATION_JOBS_LINK, "創建導航任務鏈接時出錯", "Error When Create Navigation Jobs Link", "", "", ""),
            new clsAlarmCode(ALARMS.EQ_UNLOAD_REQUEST_ON_BUT_TAG_NOT_EXIST_ON_MAP, "設備卸載請求啟動但標籤在地圖上不存在", "EQ Unload Request On But Tag Not Exist On Map", "", "", ""),
            new clsAlarmCode(ALARMS.EQ_UNLOAD_REQUEST_ON_BUT_STATION_TYPE_SETTING_IS_NOT_EQ, "設備卸載請求啟動但站點類型設置不正確", "EQ Unload Request On But Station Type Setting Is Not EQ", "", "", ""),
            new clsAlarmCode(ALARMS.ERROR_WHEN_FIND_TAG_OF_STATION, "查找站點標籤時出錯", "Error When Find Tag Of Station", "", "", ""),
            new clsAlarmCode(ALARMS.MAP_POINT_NO_TARGETS, "地圖點沒有目標", "Map Point No Targets", "", "", ""),
            new clsAlarmCode(ALARMS.ERROR_WHEN_AGV_STATUS_WRITE_TO_DB, "寫入 AGV 狀態到數據庫時出錯", "Error When AGV Status Write To DB", "", "", ""),
            new clsAlarmCode(ALARMS.TRAFFIC_ABORT, "交通中止", "Traffic Abort", "", "", ""),
            new clsAlarmCode(ALARMS.GET_ONLINE_REQ_BUT_AGV_LOCATION_IS_TOO_FAR_FROM_POINT, "收到上線請求但 AGV 位置距離過遠", "Get Online Req But AGV Location Is Too Far From Point", "", "", ""),
            new clsAlarmCode(ALARMS.GET_ONLINE_REQ_BUT_AGV_LOCATION_IS_NOT_EXIST_ON_MAP, "收到上線請求但 AGV 位置在地圖上不存在", "Get Online Req But AGV Location Is Not Exist On Map", "", "", ""),
            new clsAlarmCode(ALARMS.GET_ONLINE_REQ_BUT_AGV_IS_NOT_REGISTED, "收到上線請求但 AGV 未註冊", "Get Online Req But AGV Is Not Registered", "", "", ""),
            new clsAlarmCode(ALARMS.CANNOT_DISPATCH_MOVE_TASK_IN_WORKSTATION, "無法在工作站中調度移動任務", "Cannot Dispatch Move Task In Workstation", "", "", ""),
            new clsAlarmCode(ALARMS.CANNOT_DISPATCH_LOAD_TASK_TO_NOT_EQ_STATION, "無法將加載任務調度到非設備站", "Cannot Dispatch Load Task To Not EQ Station", "", "", ""),
            new clsAlarmCode(ALARMS.CANNOT_DISPATCH_LOAD_TASK_WHEN_AGV_NO_CARGO, "當 AGV 沒有貨物時無法調度加載任務", "Cannot Dispatch Load Task When AGV No Cargo", "", "", ""),
            new clsAlarmCode(ALARMS.CANNOT_DISPATCH_UNLOAD_TASK_WHEN_AGV_HAS_CARGO, "當 AGV 有貨物時無法調度卸載任務", "Cannot Dispatch Unload Task When AGV Has Cargo", "", "", ""),
            new clsAlarmCode(ALARMS.CANNOT_DISPATCH_UNLOAD_TASK_TO_NOT_EQ_STATION, "無法將卸載任務調度到非設備站", "Cannot Dispatch Unload Task To Not EQ Station", "", "", ""),
            new clsAlarmCode(ALARMS.CANNOT_DISPATCH_CHARGE_TASK_TO_NOT_CHARGABLE_STATION, "無法將充電任務調度到不可充電的站", "Cannot Dispatch Charge Task To Not Chargeable Station", "", "", ""),
            new clsAlarmCode(ALARMS.CANNOT_DISPATCH_ORDER_BY_AGV_BAT_STATUS_CHECK, "無法根據 AGV 電池狀態檢查調度訂單", "Cannot Dispatch Order By AGV BAT Status Check", "", "", ""),
            new clsAlarmCode(ALARMS.AGV_Task_Feedback_But_Task_Name_Not_Match, "AGV 任務反饋但任務名稱不匹配", "AGV Task Feedback But Task Name Not Match", "", "", ""),
            new clsAlarmCode(ALARMS.SYSTEM_ERROR, "系統錯誤", "System Error", "", "", ""),
            new clsAlarmCode(ALARMS.CANNOT_DISPATCH_INTO_WORKSTATION_TASK_WHEN_AGV_HAS_CARGO, "當 AGV 有貨物時無法調度進入工作站的任務", "Cannot Dispatch Into Workstation Task When AGV Has Cargo", "", "", ""),
            new clsAlarmCode(ALARMS.CANNOT_DISPATCH_NORMAL_MOVE_TASK_WHEN_DESTINE_IS_WORKSTATION, "當目的地是工作站時無法調度正常移動任務", "Cannot Dispatch Normal Move Task When Destine Is Workstation", "", "", ""),
            new clsAlarmCode(ALARMS.EQ_TAG_NOT_EXIST_IN_CURRENT_MAP, "設備標籤在當前地圖中不存在", "EQ Tag Not Exist In Current Map", "", "", ""),
            new clsAlarmCode(ALARMS.SubTask_Queue_Empty_But_Try_DownloadTask_To_AGV, "子任務隊列為空但嘗試下載任務到 AGV", "SubTask Queue Empty But Try Download Task To AGV", "", "", ""),
            new clsAlarmCode(ALARMS.AGV_STATUS_DOWN, "AGV 狀態為關閉", "AGV Status Down", "", "", ""),
            new clsAlarmCode(ALARMS.CANNOT_DISPATCH_TASK_WITH_ILLEAGAL_STATUS, "無法調度非法狀態的任務", "Cannot Dispatch Task With Illegal Status", "", "", ""),
            new clsAlarmCode(ALARMS.AGV_BATTERY_LOW_LEVEL, "AGV 電池電量低", "AGV Battery Low Level", "", "", ""),
            new clsAlarmCode(ALARMS.AGV_WORKSTATION_DATA_NOT_SETTING, "AGV 工作站數據未設置", "AGV Workstation Data Not Setting", "", "", ""),
            new clsAlarmCode(ALARMS.AGV_AT_UNKNON_TAG_LOCATION, "AGV 在未知標籤位置", "AGV At Unknown Tag Location", "", "", ""),
            new clsAlarmCode(ALARMS.Task_Status_Cant_Save_To_Database, "任務狀態無法保存到數據庫", "Task Status Can't Save To Database", "", "", ""),
            new clsAlarmCode(ALARMS.Task_Cancel_Fail, "任務取消失敗", "Task Cancel Fail", "", "", ""),
            new clsAlarmCode(ALARMS.Task_Add_To_Database_Fail, "任務添加到數據庫失敗", "Task Add To Database Fail", "", "", ""),
            new clsAlarmCode(ALARMS.AGV_TCPIP_DISCONNECT, "AGV TCP/IP 斷開連接", "AGV TCP/IP Disconnect", "", "", ""),
            new clsAlarmCode(ALARMS.Save_Measure_Data_to_DB_Fail, "保存測量數據到數據庫失敗", "Save Measure Data to DB Fail", "", "", ""),
            new clsAlarmCode(ALARMS.Region_Has_No_Agv_To_Dispatch_Task, "區域內沒有 AGV 可調度任務", "Region Has No AGV To Dispatch Task", "", "", ""),
            new clsAlarmCode(ALARMS.CANNOT_DISPATCH_CARRY_TASK_WHEN_AGV_HAS_CARGO, "當 AGV 有貨物時無法調度搬運任務", "Cannot Dispatch Carry Task When AGV Has Cargo", "", "", ""),
            new clsAlarmCode(ALARMS.CANNOT_DISPATCH_LOCAL_AUTO_TRANSFER_TASK, "無法調度本地自動轉移任務", "Cannot Dispatch Local Auto Transfer Task", "", "", ""),
            new clsAlarmCode(ALARMS.Source_Eq_Unload_Request_Off, "源設備卸載請求關閉", "Source EQ Unload Request Off", "", "", ""),
            new clsAlarmCode(ALARMS.Destine_Eq_Load_Request_Off, "目的地設備加載請求關閉", "Destine EQ Load Request Off", "", "", ""),
            new clsAlarmCode(ALARMS.Source_Eq_Status_Down, "源設備狀態關閉", "Source EQ Status Down", "", "", ""),
            new clsAlarmCode(ALARMS.Destine_Eq_Status_Down, "目的地設備狀態關閉", "Destine EQ Status Down", "", "", ""),
            new clsAlarmCode(ALARMS.Cannot_Auto_Parking_When_AGV_Has_Cargo, "當 AGV 有貨物時無法自動停車", "Cannot Auto Parking When AGV Has Cargo", "", "", ""),
            new clsAlarmCode(ALARMS.Destine_Eq_Already_Has_Task_To_Excute, "目的地設備已經有任務執行", "Destine EQ Already Has Task To Execute", "", "", ""),
            new clsAlarmCode(ALARMS.Destine_EQ_Has_AGV, "目的地設備有 AGV", "Destine EQ Has AGV", "", "", ""),
            new clsAlarmCode(ALARMS.Destine_EQ_Has_Registed, "目的地設備已註冊", "Destine EQ Has Registered", "", "", ""),
            new clsAlarmCode(ALARMS.UNLOAD_BUT_AGV_NO_CARGO_MOUNTED, "卸載但 AGV 沒有貨物安裝", "Unload But AGV No Cargo Mounted", "", "", ""),
            new clsAlarmCode(ALARMS.UNLOAD_BUT_CARGO_ID_EMPTY, "卸載但貨物 ID 為空", "Unload But Cargo ID Empty", "", "", ""),
            new clsAlarmCode(ALARMS.UNLOAD_BUT_CARGO_ID_NOT_MATCHED, "卸載但貨物 ID 不匹配", "Unload But Cargo ID Not Matched", "", "", ""),
            new clsAlarmCode(ALARMS.TASK_DOWNLOAD_DATA_ILLEAGAL, "任務下載數據非法", "Task Download Data Illegal", "", "", ""),
            new clsAlarmCode(ALARMS.AGV_TaskFeedback_ERROR, "AGV 任務反饋錯誤", "AGV TaskFeedback Error", "", "", ""),
            new clsAlarmCode(ALARMS.EQ_Disconnect, "設備斷開連接", "EQ Disconnect", "", "", ""),
            new clsAlarmCode(ALARMS.ERROR_WHEN_TASK_STATUS_CHAGE_DB, "任務狀態更改數據庫時出錯", "Error When Task Status Change DB", "", "", ""),
            new clsAlarmCode(ALARMS.Destine_Normal_Station_Has_Task_To_Reach, "目的地普通站有任務要到達", "Destine Normal Station Has Task To Reach", "", "", ""),
            new clsAlarmCode(ALARMS.Destine_Eq_Station_Has_Task_To_Park, "目的地設備站有任務要停放", "Destine EQ Station Has Task To Park", "", "", ""),
            new clsAlarmCode(ALARMS.Destine_Charge_Station_Has_AGV, "目的地充電站有 AGV", "Destine Charge Station Has AGV", "", "", ""),
            new clsAlarmCode(ALARMS.Download_Task_To_AGV_Fail, "下載任務到 AGV 失敗", "Download Task To AGV Fail", "", "", ""),
            new clsAlarmCode(ALARMS.EQ_LOAD_REQUEST_ON_BUT_HAS_CARGO, "設備加載請求啟動但有貨物", "EQ Load Request On But Has Cargo", "", "", ""),
            new clsAlarmCode(ALARMS.EQ_UNLOAD_REQUEST_ON_BUT_NO_CARGO, "設備卸載請求啟動但沒有貨物", "EQ Unload Request On But No Cargo", "", "", ""),
            new clsAlarmCode(ALARMS.EQ_UNLOAD_REQUEST_ON_BUT_POSE_NOT_UP, "設備卸載請求啟動但姿勢未上升", "EQ Unload Request On But Pose Not Up", "", "", ""),
            new clsAlarmCode(ALARMS.EQ_LOAD_REQUEST_ON_BUT_POSE_NOT_DOWN, "設備加載請求啟動但姿勢未下降", "EQ Load Request On But Pose Not Down", "", "", ""),
            new clsAlarmCode(ALARMS.EQ_UNLOAD_REQ_BUT_RACK_FULL_OR_EMPTY_IS_UNKNOWN, "設備卸載請求但架子滿或空狀態未知", "EQ Unload Req But Rack Full Or Empty Is Unknown", "", "", ""),
            new clsAlarmCode(ALARMS.EQ_LOAD_REQ_BUT_RACK_FULL_OR_EMPTY_IS_UNKNOWN, "設備加載請求但架子滿或空狀態未知", "EQ Load Req But Rack Full Or Empty Is Unknown", "", "", ""),
            new clsAlarmCode(ALARMS.AGV_Type_Is_Not_Allow_To_Execute_Task_At_Source_Equipment, "AGV 類型不允許在源設備執行任務", "AGV Type Is Not Allow To Execute Task At Source Equipment", "", "", ""),
            new clsAlarmCode(ALARMS.AGV_Type_Is_Not_Allow_To_Execute_Task_At_Destine_Equipment, "AGV 類型不允許在目的地設備執行任務", "AGV Type Is Not Allow To Execute Task At Destine Equipment", "", "", ""),
            new clsAlarmCode(ALARMS.EQ_Input_Data_Not_Enough, "設備輸入數據不足", "EQ Input Data Not Enough", "", "", ""),
            new clsAlarmCode(ALARMS.AGV_Already_Has_Charge_Task, "AGV 已經有充電任務", "AGV Already Has Charge Task", "", "", ""),
            new clsAlarmCode(ALARMS.Charge_Station_Already_Has_Task_Assigned, "充電站已經有任務分配", "Charge Station Already Has Task Assigned", "", "", ""),
            new clsAlarmCode(ALARMS.Charge_Station_Already_Has_AGV_Parked, "充電站已經有 AGV 停放", "Charge Station Already Has AGV Parked", "", "", ""),
            new clsAlarmCode(ALARMS.Station_Disabled, "站點已禁用", "Station Disabled", "", "", ""),
            new clsAlarmCode(ALARMS.TASK_DOWNLOAD_TO_AGV_FAIL_AGV_STATUS_DOWN, "下載任務到 AGV 失敗，AGV 狀態關閉", "TASK DOWNLOAD TO AGV FAIL AGV STATUS DOWN", "", "", ""),
            new clsAlarmCode(ALARMS.TASK_DOWNLOAD_TO_AGV_FAIL, "下載任務到 AGV 失敗", "TASK DOWNLOAD TO AGV FAIL", "", "", ""),
            new clsAlarmCode(ALARMS.TASK_DOWNLOAD_TO_AGV_FAIL_AGV_NOT_ON_TAG, "下載任務到 AGV 失敗，AGV 不在標籤上", "TASK DOWNLOAD TO AGV FAIL AGV NOT ON TAG", "", "", ""),
            new clsAlarmCode(ALARMS.TASK_DOWNLOAD_TO_AGV_FAIL_WORKSTATION_NOT_SETTING_YET, "下載任務到 AGV 失敗，工作站尚未設置", "TASK DOWNLOAD TO AGV FAIL WORKSTATION NOT SETTING YET", "", "", ""),
            new clsAlarmCode(ALARMS.TASK_DOWNLOAD_TO_AGV_FAIL_AGV_BATTERY_LOW_LEVEL, "下載任務到 AGV 失敗，AGV 電池電量低", "TASK DOWNLOAD TO AGV FAIL AGV BATTERY LOW LEVEL", "", "", ""),
            new clsAlarmCode(ALARMS.TASK_DOWNLOAD_TO_AGV_FAIL_AGV_CANNOT_GO_TO_WORKSTATION_WITH_NORMAL_MOVE_ACTION, "下載任務到 AGV 失敗，AGV 無法以正常移動動作前往工作站", "TASK DOWNLOAD TO AGV FAIL AGV CANNOT GO TO WORKSTATION WITH NORMAL MOVE ACTION", "", "", ""),
            new clsAlarmCode(ALARMS.TASK_DOWNLOAD_TO_AGV_FAIL_TASK_DOWNLOAD_DATA_ILLEAGAL, "下載任務到 AGV 失敗，任務下載數據非法", "TASK DOWNLOAD TO AGV FAIL TASK DOWNLOAD DATA ILLEGAL", "", "", ""),
            new clsAlarmCode(ALARMS.TASK_DOWNLOAD_TO_AGV_FAIL_SYSTEM_EXCEPTION, "下載任務到 AGV 失敗，系統異常", "TASK DOWNLOAD TO AGV FAIL SYSTEM EXCEPTION", "", "", ""),
            new clsAlarmCode(ALARMS.TASK_DOWNLOAD_TO_AGV_FAIL_NO_PATH_FOR_NAVIGATION, "下載任務到 AGV 失敗，導航無路徑", "TASK DOWNLOAD TO AGV FAIL NO PATH FOR NAVIGATION", "", "", ""),
            new clsAlarmCode(ALARMS.TASK_DOWNLOAD_TO_AGV_FAIL_TASK_CANCEL, "下載任務到 AGV 失敗，任務取消", "TASK DOWNLOAD TO AGV FAIL TASK CANCEL", "", "", ""),
            new clsAlarmCode(ALARMS.TASK_DOWNLOAD_TO_AGV_FAIL_TASK_DOWN_LOAD_TIMEOUT, "下載任務到 AGV 失敗，任務下載超時", "TASK DOWNLOAD TO AGV FAIL TASK DOWN LOAD TIMEOUT", "", "", ""),
            new clsAlarmCode(ALARMS.Task_Canceled, "任務已取消", "Task Canceled", "", "", ""),
            new clsAlarmCode(ALARMS.CANT_AUTO_SEARCH_STATION_TYPE_IS_NOT_EXCHANGE_FOR_INSPECTION_AGV, "無法自動搜索，站點類型不是檢驗 AGV 的交換站", "CANT AUTO SEARCH STATION TYPE IS NOT EXCHANGE FOR INSPECTION AGV", "", "", ""),
            new clsAlarmCode(ALARMS.NO_AVAILABLE_BAT_EXCHANGER_USABLE, "沒有可用的電池交換站", "NO AVAILABLE BAT EXCHANGER USABLE", "", "", ""),
            new clsAlarmCode(ALARMS.REGIST_REGIONS_TO_PARTS_SYSTEM_FAIL, "將區域註冊到 PARTS 系統失敗", "REGIST REGIONS TO PARTS SYSTEM FAIL", "", "", ""),
            new clsAlarmCode(ALARMS.SYSTEM_EQP_MANAGEMENT_INITIALIZE_FAIL_WITH_EXCEPTION, "系統設備管理初始化失敗並出現異常", "SYSTEM EQP MANAGEMENT INITIALIZE FAIL WITH EXCEPTION", "", "", ""),
            new clsAlarmCode(ALARMS.INVALID_CHARGE_STATION, "無效的充電站", "INVALID CHARGE STATION", "", "", ""),
            new clsAlarmCode(ALARMS.Battery_Not_Connect, "電池未連接", "Battery Not Connect", "", "", ""),
            new clsAlarmCode(ALARMS.Rack_Port_Sensor_Flash, "料架 Sensor 閃爍", "Rack Port Sensor Flash", "", "", ""),
            new clsAlarmCode(ALARMS.Transfer_Tags_Not_Found, "未找到轉換站 TAG", "Transfer Tags Not Found", "", "", ""),
            new clsAlarmCode(ALARMS.No_Transfer_Station_To_Work, "無工作轉移站", "No Transfer Station To Work", "", "", ""),
            new clsAlarmCode(ALARMS.Task_Aborted, "任務中止", "Task Aborted", "", "", ""),
            new clsAlarmCode(ALARMS.VEHICLES_TRAJECTORY_CONFLIC, "車輛軌跡衝突", "Vehicles Trajectory Conflict", "", "", ""),
            new clsAlarmCode(ALARMS.VMSDisconnectwithVehicle, "AGV與VMS斷線", "AGV Disconnect", "", "", ""),
            new clsAlarmCode(ALARMS.Charge_Station_EMO, "充電站EMO", "Charger EMO", "", "", ""),
            new clsAlarmCode(ALARMS.Charge_Station_Air_Error, "充電站氣壓異常", "Charger Air Pressure Abnormal", "", "", ""),
            new clsAlarmCode(ALARMS.Charge_Station_Smoke_Detected, "充電站偵煙異常", "Charger Smoke Detected", "", "", ""),
            new clsAlarmCode(ALARMS.TrafficAbort, "交管異常停止", "Task Failure Because Traffic Error", "", "", ""),
        };
    }
}
